providers = ["python"]

[python]
version = "3.11"

[phases.setup]
# Ставим сам Python + pip/setuptools/wheel из nixpkgs, и системные либы
nixPkgs = [
  "python311",
  "python311Packages.pip",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "gcc",
  "pkg-config",
  "portaudio",  # если pyaudio всё ещё в requirements; иначе уберите
  "ffmpeg",
  "openssl"
]

[phases.install]
cmds = [
  "python3 -V",
  "python3 -c 'import ssl; print(\"SSL OK\", ssl.OPENSSL_VERSION)'",

  # теперь pip точно есть
  "pip3 --version",
  "pip3 install --upgrade pip setuptools wheel",

  # ставим заранее биндинги OpenSSL (нек-рые пакеты импортят их в setup.py)
  "pip3 install --no-cache-dir pyOpenSSL",

  # устанавливаем зависимости проекта с подробным логом
  "pip3 install --no-cache-dir -v -r requirements.txt"
]
