providers = ["python"]

[python]
version = "3.11"

[phases.setup]
# Гарантируем наличие интерпретатора и системных либ
nixPkgs = [
  "python311",  # <— ставим сам Python 3.11 в образ
  "gcc",
  "pkg-config",
  "portaudio",  # если оставляете pyaudio; иначе уберите
  "ffmpeg",     # для pydub
  "openssl"
]

[phases.install]
cmds = [
  # Диагностика: проверим, что Python есть и SSL работает
  "python3 -V",
  "python3 -c 'import ssl; print(\"SSL OK\", ssl.OPENSSL_VERSION)'",

  # Апдейт инструментов сборки
  "python3 -m pip install --upgrade pip setuptools wheel",
  # Ставим заранее OpenSSL биндинги — некоторые пакеты импортят их в setup.py
  "python3 -m pip install --no-cache-dir pyOpenSSL",

  # Ставим зависимости проекта (с подробным логом)
  "python3 -m pip install --no-cache-dir -v -r requirements.txt"
]
