providers = ["python"]

[python]
version = "3.11"

[phases.setup]
# системные библиотеки (минимально нужное под ваш стек)
nixPkgs = [
  "gcc",
  "pkg-config",
  "portaudio",  # для pyaudio; если pyaudio уберёте — строку тоже можно убрать
  "ffmpeg",     # для pydub (gTTS/аудио)
  "openssl"
]

[phases.install]
cmds = [
  # Диагностика (увидим версию питона и SSL)
  "python -V",
  "python -c 'import ssl; print(\"SSL OK\", ssl.OPENSSL_VERSION)'",
  # Апдейт инструментов сборки
  "python -m pip install --upgrade pip setuptools wheel",
  "pip --version",
  # Ставим pyOpenSSL заранее, если кто-то импортит его в setup.py
  "pip install --no-cache-dir pyOpenSSL",
  # Побольше логов, чтобы видеть точный пакет, на котором падает
  "pip install --no-cache-dir -v -r requirements.txt"
]
